# -*- coding: utf-8 -*-
"""prog2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3cP-7D2dLWDSa9_ZVmFRbZsYt49SFBS
"""

import matplotlib.pyplot as plt
import numpy as np
m = 0
b = 0
x = np.linspace(-5,5,100)
y = m*x+b
plt.plot(x, y, '-r', label='y=mx+b')
plt.title('Graph of y=mx+b')
plt.xlabel('x', color='#1C2833')
plt.ylabel('y', color='#1C2833')
plt.legend(loc='upper left')
plt.grid()
plt.show()