# -*- coding: utf-8 -*-
"""prog1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QaTvBaxzi3tkj2YyNbPldxKjNhZxIjix
"""

a = 1
b = 1
c = a + b
print (c)

